[tool.poetry]
name = "mlserver-mlflow"
version = "1.4.0.dev2"
description = "MLflow runtime for MLServer"
authors = ["Seldon Technologies Ltd. <hello@seldon.io>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "mlserver_mlflow"}]

[tool.poetry.dependencies]
python = "^3.8"
mlserver = "*"
mlflow = "*"


[tool.poetry.group.dev.dependencies]
torch = "2.0.0"
pytorch-lightning = "2.0.3"
torchmetrics = "0.11.4"
torchvision = "0.15.1"
mlflow = "2.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
