[tool.poetry]
name = "mlserver-huggingface"
version = "1.4.0.dev2"
description = "HuggingFace runtime for MLServer"
authors = ["Seldon Technologies Ltd. <hello@seldon.io>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "mlserver_huggingface"}]

[tool.poetry.dependencies]
python = "^3.8.1,<3.12"
mlserver = "*"
tensorflow = "*"
pillow = "*"
optimum = {extras = ["onnxruntime"], version = "^1.4.0,<1.9.0"}

[tool.poetry.group.dev.dependencies]
torch = "1.13.1"
transformers = "~4.30.0"
tensorflow = "~2.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
