[tool.poetry]
name = "mlserver-huggingface"
version = "1.4.0.dev1"
description = "HuggingFace runtime for MLServer"
authors = ["Seldon Technologies Ltd. <hello@seldon.io>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "mlserver_huggingface"}]

[tool.poetry.dependencies]
python = "^3.8.1,<3.12"
mlserver = "*"
tensorflow = "*"
pillow = "*"
optimum = {extras = ["onnxruntime"], version = "^1.4.0,<1.9.0"}

[tool.poetry.group.dev.dependencies]
torch = "2.0.0"
## NOTE: Installing `main` until this PR makes it to `4.30.0`
## https://github.com/huggingface/transformers/pull/22759
transformers = {extras = ["sentencepiece"], git = "https://github.com/huggingface/transformers.git", branch = "main", rev = "0c65fb7cfa1258fb5946c5ae4d13f5a2a88a2f56"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
