
name: old-sklearn
channels:
    - conda-forge
dependencies:
    - python == 3.18
    - scikit-learn == 0.24.2
    - joblib == 0.17.0
    - requests
    - pip
    - pip:
        - mlserver == 1.1.0
        - mlserver-sklearn == 1.1.0
